cache:
  paths:
  - .bundler/

stages:
  - lint
  - test

rubocop:
  stage: lint
  before_script:
    - gem install rubocop
  script:
    - ruby -v
    - rubocop -v
    - rubocop -c .rubocop.yml

rspec:
  stage: test
  before_script:
    - ruby -v
    - which ruby
    - gem install bundler --no-ri --no-rdoc
    - bundle install --jobs $(nproc)  "${FLAGS[@]}" --path=.bundler
  script:
    - bundle exec rspec
